version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  todo:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/todo"

volumes:
  db-data:
